window.SAVORA_DATA = (() => {
    const makeMeal = ({
        id,
        name,
        image,
        category,
        instructions,
        instructionsId,
        ingredients,
    }) => {
        const meal = {
            idMeal: `local-${id}`,
            strMeal: name,
            strMealThumb: image,
            strCategory: category,
            strArea: "Indonesia",
            strCountry: "Indonesia",
            strInstructions: instructions,
            strInstructionsId: instructionsId,
            isLocal: true,
        };
        ingredients.forEach(([ingredient, measure], index) => {
            meal[`strIngredient${index + 1}`] = ingredient;
            meal[`strMeasure${index + 1}`] = measure;
        });
        return meal;
    };

    const localMeals = [
        makeMeal({
            id: "nasi-goreng",
            name: "Nasi Goreng",
            category: "Rice",
            image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Nasi_Goreng_Breakfast_in_Solo.JPG?width=900",
            ingredients: [
                ["Cooked rice", "2 bowls"],
                ["Eggs", "2"],
                ["Chicken, diced", "120 g"],
                ["Sweet soy sauce", "2 tbsp"],
                ["Shallots", "3"],
                ["Garlic", "2 cloves"],
                ["Red chilli", "1"],
                ["Spring onion", "1"],
                ["Cooking oil", "2 tbsp"],
            ],
            instructions:
                "Blend or finely chop the shallots, garlic, and chilli. Heat the oil in a wok and sauté the spice mixture until fragrant. Add the chicken and cook through. Push everything to one side, scramble the eggs, then add the rice. Pour in the sweet soy sauce and stir over high heat until evenly coated. Finish with spring onion and serve with cucumber, tomato, or crackers.",
            instructionsId:
                "Haluskan atau cincang bawang merah, bawang putih, dan cabai. Panaskan minyak lalu tumis bumbu hingga harum. Masukkan ayam dan masak sampai matang. Sisihkan ke tepi wajan, orak-arik telur, kemudian masukkan nasi. Tambahkan kecap manis dan aduk dengan api besar sampai merata. Tambahkan daun bawang lalu sajikan dengan timun, tomat, atau kerupuk.",
        }),
        makeMeal({
            id: "rendang",
            name: "Rendang Padang",
            category: "Beef",
            image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Rendang_daging_sapi_asli_Padang.JPG?width=900",
            ingredients: [
                ["Beef, cubed", "750 g"],
                ["Coconut milk", "800 ml"],
                ["Red chillies", "8"],
                ["Shallots", "8"],
                ["Garlic", "4 cloves"],
                ["Lemongrass", "2 stalks"],
                ["Galangal", "4 cm"],
                ["Kaffir lime leaves", "4"],
                ["Turmeric leaf", "1"],
                ["Salt", "to taste"],
            ],
            instructions:
                "Blend the chillies, shallots, garlic, and galangal into a smooth paste. Combine the paste, coconut milk, lemongrass, lime leaves, and turmeric leaf in a heavy pot. Bring to a gentle simmer. Add the beef and cook uncovered over low heat, stirring regularly, until the coconut milk reduces and the spices become dark and glossy. Continue until the beef is tender and coated in the thick seasoning.",
            instructionsId:
                "Haluskan cabai, bawang merah, bawang putih, dan lengkuas. Masukkan bumbu halus, santan, serai, daun jeruk, dan daun kunyit ke panci tebal. Didihkan perlahan. Masukkan daging lalu masak tanpa tutup dengan api kecil sambil sering diaduk hingga santan menyusut dan bumbu menghitam serta berminyak. Lanjutkan sampai daging empuk dan terbalut bumbu kental.",
        }),
        makeMeal({
            id: "soto-ayam",
            name: "Soto Ayam",
            category: "Soup",
            image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Soto_ayam.JPG?width=900",
            ingredients: [
                ["Chicken", "500 g"],
                ["Water", "1.5 litres"],
                ["Turmeric", "3 cm"],
                ["Garlic", "4 cloves"],
                ["Shallots", "6"],
                ["Lemongrass", "2 stalks"],
                ["Kaffir lime leaves", "3"],
                ["Rice noodles", "150 g"],
                ["Cabbage, sliced", "150 g"],
                ["Boiled eggs", "2"],
                ["Lime", "1"],
            ],
            instructions:
                "Simmer the chicken in water until tender, then remove and shred it. Blend turmeric, garlic, and shallots. Sauté the paste with lemongrass and lime leaves until fragrant, then add it to the broth. Season and simmer for 15 minutes. Arrange noodles, cabbage, shredded chicken, and egg in bowls. Ladle over the hot golden broth and finish with lime.",
            instructionsId:
                "Rebus ayam hingga empuk, lalu angkat dan suwir. Haluskan kunyit, bawang putih, dan bawang merah. Tumis bumbu bersama serai dan daun jeruk hingga harum, lalu masukkan ke kaldu. Bumbui dan masak 15 menit. Tata soun, kol, ayam suwir, dan telur di mangkuk. Siram dengan kuah panas lalu beri perasan jeruk nipis.",
        }),
        makeMeal({
            id: "gado-gado",
            name: "Gado-Gado",
            category: "Vegetarian",
            image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Gado-gado.jpg?width=900",
            ingredients: [
                ["Long beans", "150 g"],
                ["Cabbage", "150 g"],
                ["Bean sprouts", "100 g"],
                ["Potatoes", "2"],
                ["Tofu", "200 g"],
                ["Tempeh", "200 g"],
                ["Boiled eggs", "2"],
                ["Roasted peanuts", "180 g"],
                ["Palm sugar", "1 tbsp"],
                ["Tamarind water", "2 tbsp"],
                ["Sweet soy sauce", "1 tbsp"],
            ],
            instructions:
                "Blanch the vegetables separately until just tender. Fry or bake the tofu and tempeh, then cut into pieces. Grind the peanuts with palm sugar, tamarind water, sweet soy sauce, chilli, and enough warm water to make a creamy sauce. Arrange the vegetables, potato, tofu, tempeh, and egg on a plate. Spoon over the peanut sauce and serve with crackers.",
            instructionsId:
                "Rebus masing-masing sayuran hingga matang tetapi tetap segar. Goreng atau panggang tahu dan tempe, lalu potong-potong. Haluskan kacang bersama gula merah, air asam, kecap manis, cabai, dan air hangat secukupnya hingga menjadi saus kental. Tata sayuran, kentang, tahu, tempe, dan telur. Siram saus kacang dan sajikan dengan kerupuk.",
        }),
        makeMeal({
            id: "sate-ayam",
            name: "Sate Ayam",
            category: "Chicken",
            image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Satay-01.jpg?width=900",
            ingredients: [
                ["Chicken thigh", "500 g"],
                ["Sweet soy sauce", "4 tbsp"],
                ["Lime", "1"],
                ["Garlic", "2 cloves"],
                ["Coriander", "1 tsp"],
                ["Roasted peanuts", "150 g"],
                ["Palm sugar", "1 tbsp"],
                ["Chillies", "to taste"],
                ["Bamboo skewers", "12"],
            ],
            instructions:
                "Cut the chicken into bite-size pieces. Marinate with sweet soy sauce, lime, garlic, and coriander for at least 30 minutes. Thread onto soaked skewers and grill, turning and brushing with marinade, until lightly charred and cooked through. Grind the peanuts with chilli, palm sugar, and warm water. Serve the satay with peanut sauce and sliced shallots.",
            instructionsId:
                "Potong ayam kecil-kecil. Marinasi dengan kecap manis, jeruk nipis, bawang putih, dan ketumbar minimal 30 menit. Tusuk pada tusuk sate yang sudah direndam lalu bakar sambil dibalik dan dioles bumbu hingga matang serta sedikit berkaramel. Haluskan kacang dengan cabai, gula merah, dan air hangat. Sajikan sate bersama saus kacang dan irisan bawang merah.",
        }),
        makeMeal({
            id: "rawon",
            name: "Rawon Surabaya",
            category: "Beef",
            image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Rawon_Setan.jpg?width=900",
            ingredients: [
                ["Beef brisket", "600 g"],
                ["Water", "1.8 litres"],
                ["Keluak", "4 nuts"],
                ["Shallots", "7"],
                ["Garlic", "4 cloves"],
                ["Coriander", "1 tsp"],
                ["Turmeric", "2 cm"],
                ["Lemongrass", "2 stalks"],
                ["Kaffir lime leaves", "3"],
                ["Bean sprouts", "for serving"],
            ],
            instructions:
                "Simmer the beef until tender, reserving the broth. Blend keluak flesh with shallots, garlic, coriander, and turmeric. Sauté the paste with lemongrass and lime leaves until aromatic. Add it to the broth, return the sliced beef, and simmer for 25 minutes. Season well and serve hot with rice, bean sprouts, salted egg, and sambal.",
            instructionsId:
                "Rebus daging hingga empuk dan simpan kaldunya. Haluskan isi keluak bersama bawang merah, bawang putih, ketumbar, dan kunyit. Tumis bumbu dengan serai dan daun jeruk hingga harum. Masukkan ke kaldu, tambahkan kembali irisan daging, lalu masak 25 menit. Bumbui dan sajikan panas bersama nasi, tauge pendek, telur asin, dan sambal.",
        }),
    ];

    const regions = [
        { id: "world", flag: "🌐", color: "#8b67d5", areas: ["*"] },
        { id: "indonesia", flag: "🇮🇩", color: "#e94b45", areas: [] },
        { id: "uk", flag: "🇬🇧", color: "#4567c9", areas: ["British"] },
        {
            id: "europe",
            flag: "🇪🇺",
            color: "#4169d9",
            areas: [
                "Italian",
                "French",
                "Spanish",
                "Greek",
                "Dutch",
                "Polish",
                "Portuguese",
                "Croatian",
                "Irish",
            ],
        },
        {
            id: "asia",
            flag: "🌏",
            color: "#e59b2f",
            areas: [
                "Japanese",
                "Chinese",
                "Thai",
                "Indian",
                "Vietnamese",
                "Malaysian",
                "Filipino",
            ],
        },
        {
            id: "americas",
            flag: "🌎",
            color: "#4b9a69",
            areas: ["American", "Canadian", "Mexican", "Jamaican"],
        },
        {
            id: "mediterranean",
            flag: "☀️",
            color: "#d97843",
            areas: ["Turkish", "Egyptian", "Moroccan", "Tunisian", "Greek"],
        },
    ];

    const translations = {
        en: {
            discover: "Discover",
            cookbook: "My cookbook",
            eyebrow: "Recipes worth remembering",
            heroTitle: "Find your next<br><em>favorite meal.</em>",
            heroDescription:
                "From quick comfort food to dishes from across the world—discover exactly what you feel like cooking.",
            searchPlaceholder: "Search any dish...",
            explore: "Explore",
            popular: "Popular",
            surprise: "Surprise me",
            curated: "Curated recipes",
            cuisines: "World cuisines",
            free: "No sign-up needed",
            taste: "Explore by taste",
            craving: "What are you craving?",
            cravingDesc:
                "Pick a category and find a meal that matches your mood.",
            around: "Around the world",
            regionTitle: "Choose your food destination",
            regionDesc:
                "From Indonesian comfort food to European classics—travel through flavor.",
            handpicked: "Handpicked for you",
            today: "Recipes to try today",
            allCuisines: "All cuisines",
            loadMore: "Load more recipes",
            cantDecide: "Can't decide?",
            chance: "Let chance choose<br><em>your next meal.</em>",
            chanceDesc: "One click. One random recipe. A whole new favorite.",
            footer: "Good food starts with a little inspiration.",
            back: "Back to top ↑",
            results: "Showing {shown} of {total} delicious results",
            inspiration: "Recipe inspiration",
            viewRecipe: "View recipe →",
            ingredients: "Ingredients",
            cuisine: "Cuisine",
            category: "Category",
            method: "Method",
            save: "Save",
            saved: "Saved",
            share: "Share",
            loading: "Preparing your recipe…",
            fetching: "Fetching ingredients and instructions.",
            empty: "Your cookbook is empty",
            emptyDesc:
                "Save recipes with the heart button and they will appear here.",
            noResults: "No recipes found",
            noResultsDesc: "Try a different dish, category, or cuisine.",
            indonesia: "Indonesia",
            indonesiaDesc: "Rendang, nasi goreng, soto, and more",
            uk: "UK & England",
            ukDesc: "Roasts, pies, puddings, and classics",
            europe: "Europe",
            europeDesc: "Italian, French, Spanish, Greek, and more",
            asia: "Asia",
            asiaDesc: "Japanese, Thai, Indian, and more",
            americas: "The Americas",
            americasDesc: "American, Mexican, Canadian, Caribbean",
            mediterranean: "Mediterranean & MENA",
            mediterraneanDesc: "Turkish, Egyptian, Moroccan, Greek",
        },
        id: {
            discover: "Jelajahi",
            cookbook: "Buku resepku",
            eyebrow: "Resep yang layak dikenang",
            heroTitle: "Temukan makanan<br><em>favorit berikutnya.</em>",
            heroDescription:
                "Dari makanan rumahan hingga hidangan dari berbagai negara—temukan menu yang ingin kamu masak.",
            searchPlaceholder: "Cari makanan apa saja...",
            explore: "Cari",
            popular: "Populer",
            surprise: "Pilihkan acak",
            curated: "Resep pilihan",
            cuisines: "Kuliner dunia",
            free: "Tanpa perlu daftar",
            taste: "Jelajahi berdasarkan rasa",
            craving: "Kamu sedang ingin makan apa?",
            cravingDesc:
                "Pilih kategori dan temukan makanan yang sesuai dengan suasana hatimu.",
            around: "Keliling dunia",
            regionTitle: "Pilih destinasi kulinermu",
            regionDesc:
                "Dari makanan Indonesia hingga hidangan klasik Eropa—jelajahi dunia lewat rasa.",
            handpicked: "Pilihan khusus untukmu",
            today: "Resep untuk dicoba hari ini",
            allCuisines: "Semua negara",
            loadMore: "Tampilkan lebih banyak",
            cantDecide: "Masih bingung?",
            chance: "Biarkan kejutan memilih<br><em>makananmu berikutnya.</em>",
            chanceDesc:
                "Satu klik, satu resep acak, satu calon makanan favorit baru.",
            footer: "Makanan enak dimulai dari sedikit inspirasi.",
            back: "Kembali ke atas ↑",
            results: "Menampilkan {shown} dari {total} hasil",
            inspiration: "Inspirasi resep",
            viewRecipe: "Lihat resep →",
            ingredients: "Bahan-bahan",
            cuisine: "Asal kuliner",
            category: "Kategori",
            method: "Cara memasak",
            save: "Simpan",
            saved: "Tersimpan",
            share: "Bagikan",
            loading: "Menyiapkan resepmu…",
            fetching: "Mengambil bahan dan cara memasak.",
            empty: "Buku resepmu masih kosong",
            emptyDesc: "Tekan tombol hati untuk menyimpan resep di sini.",
            noResults: "Resep tidak ditemukan",
            noResultsDesc: "Coba makanan, kategori, atau negara lain.",
            indonesia: "Indonesia",
            indonesiaDesc: "Rendang, nasi goreng, soto, dan lainnya",
            uk: "UK & Inggris",
            ukDesc: "Roast, pie, pudding, dan hidangan klasik",
            europe: "Eropa",
            europeDesc: "Italia, Prancis, Spanyol, Yunani, dan lainnya",
            asia: "Asia",
            asiaDesc: "Jepang, Thailand, India, dan lainnya",
            americas: "Amerika",
            americasDesc: "Amerika Serikat, Meksiko, Kanada, Karibia",
            mediterranean: "Mediterania & Timur Tengah",
            mediterraneanDesc: "Turki, Mesir, Maroko, dan Yunani",
        },
        es: {
            discover: "Descubrir",
            cookbook: "Mi recetario",
            eyebrow: "Recetas para recordar",
            heroTitle: "Encuentra tu próxima<br><em>comida favorita.</em>",
            heroDescription:
                "Desde comida casera hasta platos del mundo—encuentra exactamente lo que quieres cocinar.",
            searchPlaceholder: "Busca cualquier plato...",
            explore: "Explorar",
            popular: "Popular",
            surprise: "Sorpréndeme",
            curated: "Recetas seleccionadas",
            cuisines: "Cocinas del mundo",
            free: "Sin registro",
            taste: "Explora por sabor",
            craving: "¿Qué te apetece?",
            cravingDesc:
                "Elige una categoría y encuentra una comida para tu estado de ánimo.",
            around: "Alrededor del mundo",
            regionTitle: "Elige tu destino gastronómico",
            regionDesc:
                "De Indonesia a los clásicos europeos—viaja a través del sabor.",
            handpicked: "Elegido para ti",
            today: "Recetas para probar hoy",
            allCuisines: "Todas las cocinas",
            loadMore: "Ver más recetas",
            cantDecide: "¿No puedes decidir?",
            chance: "Deja que el azar elija<br><em>tu próxima comida.</em>",
            chanceDesc: "Un clic, una receta al azar, un nuevo favorito.",
            footer: "La buena comida empieza con inspiración.",
            back: "Volver arriba ↑",
            results: "Mostrando {shown} de {total} resultados",
            inspiration: "Inspiración",
            viewRecipe: "Ver receta →",
            ingredients: "Ingredientes",
            cuisine: "Cocina",
            category: "Categoría",
            method: "Preparación",
            save: "Guardar",
            saved: "Guardado",
            share: "Compartir",
            loading: "Preparando tu receta…",
            fetching: "Cargando ingredientes e instrucciones.",
            empty: "Tu recetario está vacío",
            emptyDesc: "Guarda recetas con el botón de corazón.",
            noResults: "No se encontraron recetas",
            noResultsDesc: "Prueba otro plato, categoría o cocina.",
            indonesia: "Indonesia",
            indonesiaDesc: "Rendang, nasi goreng, soto y más",
            uk: "Reino Unido e Inglaterra",
            ukDesc: "Asados, pasteles y clásicos británicos",
            europe: "Europa",
            europeDesc: "Italia, Francia, España, Grecia y más",
            asia: "Asia",
            asiaDesc: "Japón, Tailandia, India y más",
            americas: "Las Américas",
            americasDesc: "EE. UU., México, Canadá y el Caribe",
            mediterranean: "Mediterráneo y MENA",
            mediterraneanDesc: "Turquía, Egipto, Marruecos y Grecia",
        },
        fr: {
            discover: "Découvrir",
            cookbook: "Mon livre",
            eyebrow: "Des recettes inoubliables",
            heroTitle: "Trouvez votre prochain<br><em>plat préféré.</em>",
            heroDescription:
                "Des plats réconfortants aux cuisines du monde—trouvez exactement quoi cuisiner.",
            searchPlaceholder: "Rechercher un plat...",
            explore: "Explorer",
            popular: "Populaire",
            surprise: "Surprenez-moi",
            curated: "Recettes sélectionnées",
            cuisines: "Cuisines du monde",
            free: "Sans inscription",
            taste: "Explorer par goût",
            craving: "De quoi avez-vous envie ?",
            cravingDesc: "Choisissez une catégorie selon votre humeur.",
            around: "Autour du monde",
            regionTitle: "Choisissez votre destination culinaire",
            regionDesc:
                "De l'Indonésie aux classiques européens—voyagez par les saveurs.",
            handpicked: "Choisi pour vous",
            today: "Recettes à essayer aujourd'hui",
            allCuisines: "Toutes les cuisines",
            loadMore: "Voir plus de recettes",
            cantDecide: "Vous hésitez ?",
            chance: "Laissez le hasard choisir<br><em>votre prochain repas.</em>",
            chanceDesc: "Un clic, une recette aléatoire, un nouveau favori.",
            footer: "La bonne cuisine commence par l'inspiration.",
            back: "Retour en haut ↑",
            results: "Affichage de {shown} sur {total} résultats",
            inspiration: "Inspiration recette",
            viewRecipe: "Voir la recette →",
            ingredients: "Ingrédients",
            cuisine: "Cuisine",
            category: "Catégorie",
            method: "Préparation",
            save: "Enregistrer",
            saved: "Enregistré",
            share: "Partager",
            loading: "Préparation de votre recette…",
            fetching: "Chargement des ingrédients et instructions.",
            empty: "Votre livre est vide",
            emptyDesc: "Enregistrez des recettes avec le bouton cœur.",
            noResults: "Aucune recette trouvée",
            noResultsDesc: "Essayez un autre plat, catégorie ou cuisine.",
            indonesia: "Indonésie",
            indonesiaDesc: "Rendang, nasi goreng, soto et plus",
            uk: "Royaume-Uni et Angleterre",
            ukDesc: "Rôtis, tourtes, puddings et classiques",
            europe: "Europe",
            europeDesc: "Italie, France, Espagne, Grèce et plus",
            asia: "Asie",
            asiaDesc: "Japon, Thaïlande, Inde et plus",
            americas: "Les Amériques",
            americasDesc: "États-Unis, Mexique, Canada, Caraïbes",
            mediterranean: "Méditerranée et MENA",
            mediterraneanDesc: "Turquie, Égypte, Maroc et Grèce",
        },
    };

    Object.assign(translations.en, {
        world: "All world recipes",
        worldDesc: "Hundreds of recipes from A to Z",
        allIngredients: "All ingredients",
        sortDefault: "Featured order",
        sortAZ: "Name A–Z",
        sortZA: "Name Z–A",
        loadingCatalog: "Building the global catalog",
    });
    Object.assign(translations.id, {
        world: "Semua resep dunia",
        worldDesc: "Ratusan resep lengkap dari A sampai Z",
        allIngredients: "Semua bahan utama",
        sortDefault: "Urutan pilihan",
        sortAZ: "Nama A–Z",
        sortZA: "Nama Z–A",
        loadingCatalog: "Menyusun katalog dunia",
    });
    Object.assign(translations.es, {
        world: "Todas las recetas",
        worldDesc: "Cientos de recetas de la A a la Z",
        allIngredients: "Todos los ingredientes",
        sortDefault: "Orden destacado",
        sortAZ: "Nombre A–Z",
        sortZA: "Nombre Z–A",
        loadingCatalog: "Creando el catálogo mundial",
    });
    Object.assign(translations.fr, {
        world: "Toutes les recettes",
        worldDesc: "Des centaines de recettes de A à Z",
        allIngredients: "Tous les ingrédients",
        sortDefault: "Ordre sélectionné",
        sortAZ: "Nom A–Z",
        sortZA: "Nom Z–A",
        loadingCatalog: "Création du catalogue mondial",
    });

    return { localMeals, regions, translations };
})();
